# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 23:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar_id', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('deptnum', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('evals', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('description', models.TextField()),
                ('assgts', models.TextField()),
                ('grading', models.TextField()),
                ('prereqs', models.TextField()),
                ('otherinfo', models.TextField()),
                ('professors', models.TextField()),
                ('area', models.CharField(max_length=3)),
                ('pdfable', models.BooleanField(default=True)),
                ('pdfonly', models.BooleanField(default=False)),
                ('auditable', models.BooleanField(default=True)),
                ('pdfaudit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faves', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
