# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
