# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170411_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='papers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='participation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='takehome',
            field=models.BooleanField(default=True),
        ),
    ]
