# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170413_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='midterm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pset',
            field=models.BooleanField(default=True),
        ),
    ]
